# Generated by Django 4.1.3 on 2022-11-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("static", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedJobs",
            fields=[
                (
                    "saved_job_ID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("employerID", models.IntegerField(default=0)),
                ("employerName", models.CharField(max_length=200)),
                ("expirationDate", models.CharField(max_length=200)),
                ("jobDescription", models.CharField(max_length=20000)),
                ("jobID", models.IntegerField(default=0)),
                ("jobTitle", models.CharField(max_length=200)),
                ("jobURL", models.URLField()),
                ("locationName", models.CharField(max_length=100)),
                ("maximumSalary", models.IntegerField(default=0)),
                ("minimumSalary", models.IntegerField(default=0)),
                ("applied_for_job", models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "user_ID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("username", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=200)),
                ("first_name", models.CharField(max_length=500)),
                ("email", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(old_name="JobsList", new_name="JobsSearchDB",),
        migrations.DeleteModel(name="JobsItem",),
        migrations.AddField(
            model_name="savedjobs",
            name="Saved_user_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="static.users"
            ),
        ),
        migrations.AddField(
            model_name="savedjobs",
            name="jobsDB",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="static.jobssearchdb"
            ),
        ),
    ]
